# Minimal PHP example for Kata
# - Serves a tiny PHP endpoint via the built-in server
# - Traefik labels are generated automatically; host defaults to <app>.localhost

environment:
  PORT: "8000"
  DOCROOT: "/app/public"

traefik:
  host: "app.localhost"   # change to your domain
  service: web
  port: 8000
  entrypoints: ["web"]
  enable_http_redirect: false
  tls: false

services:
  web:
    runtime: php
    command: php -S 0.0.0.0:${PORT} -t ${DOCROOT}
    expose:
      - "${PORT}"
