# Minimal Python example for Kata
# - Runs a FastAPI app with Uvicorn
# - Traefik labels are generated automatically; host defaults to <app>.localhost

environment:
  PORT: "8000"

traefik:
  host: "app.localhost"   # change to your domain
  service: web
  port: 8000
  entrypoints: ["websecure"]
  enable_http_redirect: true

services:
  web:
    runtime: python
    command: uvicorn app:app --host 0.0.0.0 --port ${PORT}
    expose:
      - "${PORT}"
